In [1]:
# Eli Standard
# Ben Huston
# CS287 Final Project
# 4/14/22

In [2]:
# Import pandas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# For our project we wanted to work with data from the NBA
# We found this dataset from BasketballReference.com called '2020-21 NBA Player Stats: Per Game'
# It contains 540 players from the 2020-21 season and includes 28 features for in-game stats like 
# position, age, minutes played, rebounds, points

df = pd.read_csv("basketballref2020.csv")

# Get the summary
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 706 entries, 0 to 705
Data columns (total 30 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Rk      706 non-null    object
 1   Player  705 non-null    object
 2   Pos     705 non-null    object
 3   Age     705 non-null    float64
 4   Tm      705 non-null    object
 5   G       705 non-null    float64
 6   GS      705 non-null    float64
 7   MP      705 non-null    float64
 8   FG      705 non-null    float64
 9   FGA     705 non-null    float64
 10  FG%     703 non-null    float64
 11  3P      705 non-null    float64
 12  3PA     705 non-null    float64
 13  3P%     670 non-null    float64
 14  2P      705 non-null    float64
 15  2PA     705 non-null    float64
 16  2P%     699 non-null    float64
 17  eFG%    703 non-null    float64
 18  FT      705 non-null    float64
 19  FTA     705 non-null    float64
 20  FT%     676 non-null    float64
 21  ORB     705 non-null    float64
 22  DRB     705 non-null    float64
 23  TRB     705 non-null    float64
 24  AST     705 non-null    float64
 25  STL     705 non-null    float64
 26  BLK     705 non-null    float64
 27  TOV     705 non-null    float64
 28  PF      705 non-null    float64
 29  PTS     705 non-null    float64
dtypes: float64(26), object(4)
memory usage: 165.6+ KB
None

In [5]:
# NBA 2k21 is a video game that simulates the current NBA players with real world stats.
# Players in 2k have an assortment of individual ratings assigned to them; for example a player will have a 
#three point shooting rating and a stealing rating among many others. The average of these individual ratings
#is encompassed by an overall (aka OVR) rating assigned to each player.

In [6]:
#We realized that in our dataset we only had 2 defensive columns (BLK and STL) accesable to us. This page: 
#https://www.basketball-reference.com/leagues/NBA_2021_advanced.html on BasketballReference.com is a dataset of the same
#players offering advanced statistics.
#By importing this dataframe and merging the two we realized we would gain 4 more defensive stats to base our
#linear regression model on.

In [7]:
# Read in new CSV with Defensive Win Shares and and Defensive Box Plus/Minus
df2 = pd.read_csv("bballadvanced.csv")

In [8]:
df2

      Rk                       Player  STL%  BLK%  DWS  DBPM
0      1   Precious Achiuwa\achiupr01   1.3   4.0  1.0  -0.5
1      2       Jaylen Adams\adamsja01   0.0   0.0  0.0  -4.6
2      3       Steven Adams\adamsst01   1.6   2.2  1.7   0.1
3      4        Bam Adebayo\adebaba01   1.7   3.2  3.2   2.0
4      5  LaMarcus Aldridge\aldrila01   0.8   3.7  0.6  -0.2
..   ...                          ...   ...   ...  ...   ...
700  536       Delon Wright\wrighde01   3.0   1.3  0.5   0.6
701  537     Thaddeus Young\youngth01   2.2   2.1  2.2   1.4
702  538         Trae Young\youngtr01   1.2   0.5  1.3  -1.7
703  539        Cody Zeller\zelleco01   1.3   1.7  1.1  -0.2
704  540        Ivica Zubac\zubaciv01   0.7   3.4  2.1   0.4

[705 rows x 6 columns]

In [9]:
#We then dropped en empty columns and assigned these new advanced statistics to new columns 
#in the original dataframe of players.

In [10]:
df=df.drop(705)

In [11]:
df["STL%"]=df2["STL%"]

In [12]:
df["BLK%"]=df2["BLK%"]

In [13]:
df["DWS"]=df2["DWS"]

In [14]:
df["DBPM"]=df2["DBPM"]

In [15]:
df

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,AST,STL,BLK,TOV,PF,PTS,STL%,BLK%,DWS,DBPM
0,1,Precious Achiuwa\achiupr01,PF,21.0,MIA,61.0,4.0,12.1,2.0,3.7,...,0.5,0.3,0.5,0.7,1.5,5.0,1.3,4.0,1.0,-0.5
1,2,Jaylen Adams\adamsja01,PG,24.0,MIL,7.0,0.0,2.6,0.1,1.1,...,0.3,0.0,0.0,0.0,0.1,0.3,0.0,0.0,0.0,-4.6
2,3,Steven Adams\adamsst01,C,27.0,NOP,58.0,58.0,27.7,3.3,5.3,...,1.9,0.9,0.7,1.3,1.9,7.6,1.6,2.2,1.7,0.1
3,4,Bam Adebayo\adebaba01,C,23.0,MIA,64.0,64.0,33.5,7.1,12.5,...,5.4,1.2,1.0,2.6,2.3,18.7,1.7,3.2,3.2,2.0
4,5,LaMarcus Aldridge\aldrila01,C,35.0,TOT,26.0,23.0,25.9,5.4,11.4,...,1.9,0.4,1.1,1.0,1.8,13.5,0.8,3.7,0.6,-0.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
700,536,Delon Wright\wrighde01,PG,28.0,SAC,27.0,8.0,25.8,3.9,8.3,...,3.6,1.6,0.4,1.3,1.1,10.0,3.0,1.3,0.5,0.6
701,537,Thaddeus Young\youngth01,PF,32.0,CHI,68.0,23.0,24.3,5.4,9.7,...,4.3,1.1,0.6,2.0,2.2,12.1,2.2,2.1,2.2,1.4
702,538,Trae Young\youngtr01,PG,22.0,ATL,63.0,63.0,33.7,7.7,17.7,...,9.4,0.8,0.2,4.1,1.8,25.3,1.2,0.5,1.3,-1.7
703,539,Cody Zeller\zelleco01,C,28.0,CHO,48.0,21.0,20.9,3.8,6.8,...,1.8,0.6,0.4,1.1,2.5,9.4,1.3,1.7,1.1,-0.2
704,540,Ivica Zubac\zubaciv01,C,23.0,LAC,72.0,33.0,22.3,3.6,5.5,...,1.3,0.3,0.9,1.1,2.6,9.0,0.7,3.4,2.1,0.4

In [ ]:
#We then performed basic cleaning on our dataset.This process mostly included cleaning individual variables so that they
#were easier for us to understand abd reordering the columns.

In [16]:
# Cleaning our dataframe began by finding a way to change the individual player's names. 
print(df["Player"])

0       Precious Achiuwa\achiupr01
1           Jaylen Adams\adamsja01
2           Steven Adams\adamsst01
3            Bam Adebayo\adebaba01
4      LaMarcus Aldridge\aldrila01
                  ...
700         Delon Wright\wrighde01
701       Thaddeus Young\youngth01
702           Trae Young\youngtr01
703          Cody Zeller\zelleco01
704          Ivica Zubac\zubaciv01
Name: Player, Length: 705, dtype: object

In [17]:
# Create a new dataframe that is a copy of the old one
dfNew = df

# Create a new column in the new dataframe that is just the player's name (without the 9 character ID code)
dfNew['Name'] = dfNew['Player'].str[:-10]
# See if it worked
print(dfNew.iloc[1:5, :])
dfNew.info()

  Rk                       Player Pos   Age   Tm     G    GS    MP   FG   FGA  \
1  2       Jaylen Adams\adamsja01  PG  24.0  MIL   7.0   0.0   2.6  0.1   1.1
2  3       Steven Adams\adamsst01   C  27.0  NOP  58.0  58.0  27.7  3.3   5.3
3  4        Bam Adebayo\adebaba01   C  23.0  MIA  64.0  64.0  33.5  7.1  12.5
4  5  LaMarcus Aldridge\aldrila01   C  35.0  TOT  26.0  23.0  25.9  5.4  11.4

   ...  STL  BLK  TOV   PF   PTS  STL%  BLK%  DWS  DBPM               Name
1  ...  0.0  0.0  0.0  0.1   0.3   0.0   0.0  0.0  -4.6       Jaylen Adams
2  ...  0.9  0.7  1.3  1.9   7.6   1.6   2.2  1.7   0.1       Steven Adams
3  ...  1.2  1.0  2.6  2.3  18.7   1.7   3.2  3.2   2.0        Bam Adebayo
4  ...  0.4  1.1  1.0  1.8  13.5   0.8   3.7  0.6  -0.2  LaMarcus Aldridge

[4 rows x 35 columns]
<class 'pandas.core.frame.DataFrame'>
Int64Index: 705 entries, 0 to 704
Data columns (total 35 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Rk      705 non-null    object
 1   Player  705 non-null    object
 2   Pos     705 non-null    object
 3   Age     705 non-null    float64
 4   Tm      705 non-null    object
 5   G       705 non-null    float64
 6   GS      705 non-null    float64
 7   MP      705 non-null    float64
 8   FG      705 non-null    float64
 9   FGA     705 non-null    float64
 10  FG%     703 non-null    float64
 11  3P      705 non-null    float64
 12  3PA     705 non-null    float64
 13  3P%     670 non-null    float64
 14  2P      705 non-null    float64
 15  2PA     705 non-null    float64
 16  2P%     699 non-null    float64
 17  eFG%    703 non-null    float64
 18  FT      705 non-null    float64
 19  FTA     705 non-null    float64
 20  FT%     676 non-null    float64
 21  ORB     705 non-null    float64
 22  DRB     705 non-null    float64
 23  TRB     705 non-null    float64
 24  AST     705 non-null    float64
 25  STL     705 non-null    float64
 26  BLK     705 non-null    float64
 27  TOV     705 non-null    float64
 28  PF      705 non-null    float64
 29  PTS     705 non-null    float64
 30  STL%    705 non-null    float64
 31  BLK%    705 non-null    float64
 32  DWS     705 non-null    float64
 33  DBPM    705 non-null    float64
 34  Name    705 non-null    object
dtypes: float64(30), object(5)
memory usage: 198.3+ KB

In [18]:
# Create a new dataframe that reorders the columns
dfReordered = dfNew[['Name','Pos','Tm','Age','G','GS','MP','FG', 'FGA','FG%','3P','3PA','3P%',
                     '2P','2PA','2P%','eFG%','FT','FTA','FT%','ORB','DRB','TRB','AST','STL','BLK','STL%',
                     'BLK%','DWS','DBPM','TOV','PF','PTS']]
# Key: Name, Position, Team, Age, Games, Games Started, Minutes Played, Field Goals, Field Goal Attempts,
# 3 Pointers, 3 Point Attempts, 3 Point Percentage, 2 Pointers, 2 Ppoint Percentage, Effective Field Goal Percentage
# Free Throws, Free Throw Attempts, Free Throw Percentage, Offensive Rebounds, Defensive Rebounds, Total Rebounds,
# Assists, Steals, Blocks, Steal Percentage, Block Percentage, Defensive Win Shares, Defensive Box Plus/Minus,
# Turnover per game, Personal Fouls, Points

print(dfReordered.head()) # [5 rows x 33 columns] - got rid of 'Rank' and Player'

                Name Pos   Tm   Age     G    GS    MP   FG   FGA    FG%  ...  \
0   Precious Achiuwa  PF  MIA  21.0  61.0   4.0  12.1  2.0   3.7  0.544  ...
1       Jaylen Adams  PG  MIL  24.0   7.0   0.0   2.6  0.1   1.1  0.125  ...
2       Steven Adams   C  NOP  27.0  58.0  58.0  27.7  3.3   5.3  0.614  ...
3        Bam Adebayo   C  MIA  23.0  64.0  64.0  33.5  7.1  12.5  0.570  ...
4  LaMarcus Aldridge   C  TOT  35.0  26.0  23.0  25.9  5.4  11.4  0.473  ...

   AST  STL  BLK  STL%  BLK%  DWS  DBPM  TOV   PF   PTS
0  0.5  0.3  0.5   1.3   4.0  1.0  -0.5  0.7  1.5   5.0
1  0.3  0.0  0.0   0.0   0.0  0.0  -4.6  0.0  0.1   0.3
2  1.9  0.9  0.7   1.6   2.2  1.7   0.1  1.3  1.9   7.6
3  5.4  1.2  1.0   1.7   3.2  3.2   2.0  2.6  2.3  18.7
4  1.9  0.4  1.1   0.8   3.7  0.6  -0.2  1.0  1.8  13.5

[5 rows x 33 columns]

In [19]:
# Make the names lowercase so the data can be merged by this column with the other dataframe that includes OVR score
dfReordered['Name'] = dfReordered['Name'].str.lower()
dfReordered['Name']

C:\Users\husto\AppData\Local\Temp/ipykernel_3068/2947717095.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfReordered['Name'] = dfReordered['Name'].str.lower()

0       precious achiuwa
1           jaylen adams
2           steven adams
3            bam adebayo
4      lamarcus aldridge
             ...
700         delon wright
701       thaddeus young
702           trae young
703          cody zeller
704          ivica zubac
Name: Name, Length: 705, dtype: object

In [ ]:
#The next step in our data collection and preprocessing was to gain a better understanding of Beautiful Soup, and use it to
#scrape the players OVR ratings from https://nba2kw.com/list/nba-2k21-all-player-ratings/.

In [ ]:
#After downloading the html of the website and reading it into our Python script using Beautiful Soup, we realized
#that the next steps in our web scraping process would actually be quite involved; as this website wasn't well cleaned
#at all. For reference here's the code that comprised that information pertaining to one player of the hundreds 
#in the data set (WE'LL THEN INCLUDE A SLIDE WITH THIS CODE IN OUR PRESENTATION).

In [ ]:
#We worked on this data set for a week and a half, but finally settled on scraping https://hoopshype.com/nba2k/2020-2021/
#instead. This dataset contained the OVR we needed from every player, but unfourtunately didnt' have their height which we
#had planned on being a predicting variable in our regression model. The methods you see us apply on the hoopshype.com 
#data set from here on out we learned toiling through working with the first one.

In [20]:
############## Read in data from https://hoopshype.com/nba2k/2020-2021/

from bs4 import BeautifulSoup
import csv
import pandas as pd
import re

df = pd.read_csv("basketballref2020.csv")
soup = BeautifulSoup(open("page2.mht"), features="lxml")

with open('readme.txt', 'w') as f:
    f.write(soup.prettify())
    f.close()

In [21]:
# Each table row in this playerrows result object holds one player in our dataset
# It needs some cleaning
playerrows=soup.find_all('tr')
print(playerrows[2])

<tr>
<td class='3D"rank"' data-value='3D""'>1.</td>
<td class='3D"name"' data-value='3D""'>
<a href='3D"https://hoopshype.com/player/giannis-antetokounmp=' o="">
									Giannis Antetokounmpo								</a>
</td>
<td class='3D"value' data-value='3D"97"' hh-salaries-sorted="">
															97													</td>
</tr>

In [22]:
# Use soup.findall with the anonymous functions to isolate the individual parts (OVR score and name)
# Start with OVR Score
overallrows = soup.find_all(lambda tag: tag.name == 'td' and tag.get('class') == ['3D"value' ])
i=0
for ovr in overallrows:
   print(ovr)
   text = ovr.renderContents()
   overallrows[i]=text
   i=i+1
# We now see all the OVR scores isolated in rows, but they have to be cleaned even more.

<td class='3D"value' hh-salaries-sorted="">2020/21</td>
<td class='3D"value' data-value='3D"97"' hh-salaries-sorted="">
															97													</td>
<td class='3D"value' data-value='3D"97"' hh-salaries-sorted="">
															97													</td>
<td class='3D"value' data-value='3D"96"' hh-salaries-sorted="">
															96													</td>
<td class='3D"value' data-value='3D"96"' hh-salaries-sorted="">
															96													</td>
<td class='3D"value' data-value='3D"95"' hh-salaries-sorted="">
															95													</td>
<td class='3D"value' data-value='3D"95"' hh-salaries-sorted="">
															95													</td>
<td class='3D"value' data-value='3D"95"' hh-salaries-sorted="">
															95													</td>
<td class='3D"value' data-value='3D"94"' hh-salaries-sorted="">
															94													</td>
<td class='3D"value' data-value='3D"94"' hh-salaries-sorted="">
															94													</td>
<td class='3D"value' data-value='3D"91"' hh-salaries-sorted="">
															91													</td>
<td class='3D"value' data-value='3D"90"' hh-salaries-sorted="">
															90													</td>
<td class='3D"value' data-value='3D"90"' hh-salaries-sorted="">
															90													</td>
<td class='3D"value' data-value='3D"90"' hh-salaries-sorted="">
															90													</td>
<td class='3D"value' data-value='3D"90"' hh-salaries-sorted="">
															90													</td>
<td class='3D"value' data-value='3D"89"' hh-salaries-sorted="">
															89													</td>
<td class='3D"value' data-value='3D"89"' hh-salaries-sorted="">
															89													</td>
<td class='3D"value' data-value='3D"88"' hh-salaries-sorted="">
															88													</td>
<td class='3D"value' data-value='3D"88"' hh-salaries-sorted="">
															88													</td>
<td class='3D"value' data-value='3D"88"' hh-salaries-sorted="">
															88													</td>
<td class='3D"value' data-value='3D"88"' hh-salaries-sorted="">
															88													</td>
<td class='3D"value' data-value='3D"88"' hh-salaries-sorted="">
															88													</td>
<td class='3D"value' data-value='3D"88"' hh-salaries-sorted="">
															88													</td>
<td class='3D"value' data-value='3D"87"' hh-salaries-sorted="">
															87													</td>
<td class='3D"value' data-value='3D"87"' hh-salaries-sorted="">
															87													</td>
<td class='3D"value' data-value='3D"87"' hh-salaries-sorted="">
															87													</td>
<td class='3D"value' data-value='3D"87"' hh-salaries-sorted="">
															87													</td>
<td class='3D"value' data-value='3D"87"' hh-salaries-sorted="">
															87													</td>
<td class='3D"value' data-value='3D"87"' hh-salaries-sorted="">
															87													</td>
<td class='3D"value' data-value='3D"86"' hh-salaries-sorted="">
															86													</td>
<td class='3D"value' data-value='3D"86"' hh-salaries-sorted="">
															86													</td>
<td class='3D"value' data-value='3D"86"' hh-salaries-sorted="">
															86													</td>
<td class='3D"value' data-value='3D"86"' hh-salaries-sorted="">
															86													</td>
<td class='3D"value' data-value='3D"86"' hh-salaries-sorted="">
															86													</td>
<td class='3D"value' data-value='3D"86"' hh-salaries-sorted="">
															86													</td>
<td class='3D"value' data-value='3D"86"' hh-salaries-sorted="">
															86													</td>
<td class='3D"value' data-value='3D"85"' hh-salaries-sorted="">
															85													</td>
<td class='3D"value' data-value='3D"85"' hh-salaries-sorted="">
															85													</td>
<td class='3D"value' data-value='3D"85"' hh-salaries-sorted="">
															85													</td>
<td class='3D"value' data-value='3D"85"' hh-salaries-sorted="">
															85													</td>
<td class='3D"value' data-value='3D"85"' hh-salaries-sorted="">
															85													</td>
<td class='3D"value' data-value='3D"85"' hh-salaries-sorted="">
															85													</td>
<td class='3D"value' data-value='3D"85"' hh-salaries-sorted="">
															85													</td>
<td class='3D"value' data-value='3D"85"' hh-salaries-sorted="">
															85													</td>
<td class='3D"value' data-value='3D"85"' hh-salaries-sorted="">
															85													</td>
<td class='3D"value' data-value='3D"84"' hh-salaries-sorted="">
															84													</td>
<td class='3D"value' data-value='3D"84"' hh-salaries-sorted="">
															84													</td>
<td class='3D"value' data-value='3D"84"' hh-salaries-sorted="">
															84													</td>
<td class='3D"value' data-value='3D"84"' hh-salaries-sorted="">
															84													</td>
<td class='3D"value' data-value='3D"84"' hh-salaries-sorted="">
															84													</td>
<td class='3D"value' data-value='3D"84"' hh-salaries-sorted="">
															84													</td>
<td class='3D"value' data-value='3D"84"' hh-salaries-sorted="">
															84													</td>
<td class='3D"value' data-value='3D"84"' hh-salaries-sorted="">
															84													</td>
<td class='3D"value' data-value='3D"83"' hh-salaries-sorted="">
															83													</td>
<td class='3D"value' data-value='3D"83"' hh-salaries-sorted="">
															83													</td>
<td class='3D"value' data-value='3D"83"' hh-salaries-sorted="">
															83													</td>
<td class='3D"value' data-value='3D"83"' hh-salaries-sorted="">
															83													</td>
<td class='3D"value' data-value='3D"83"' hh-salaries-sorted="">
															83													</td>
<td class='3D"value' data-value='3D"83"' hh-salaries-sorted="">
															83													</td>
<td class='3D"value' data-value='3D"83"' hh-salaries-sorted="">
															83													</td>
<td class='3D"value' data-value='3D"83"' hh-salaries-sorted="">
															83													</td>
<td class='3D"value' data-value='3D"83"' hh-salaries-sorted="">
															83													</td>
<td class='3D"value' data-value='3D"83"' hh-salaries-sorted="">
															83													</td>
<td class='3D"value' data-value='3D"83"' hh-salaries-sorted="">
															83													</td>
<td class='3D"value' data-value='3D"82"' hh-salaries-sorted="">
															82													</td>
<td class='3D"value' data-value='3D"82"' hh-salaries-sorted="">
															82													</td>
<td class='3D"value' data-value='3D"82"' hh-salaries-sorted="">
															82													</td>
<td class='3D"value' data-value='3D"82"' hh-salaries-sorted="">
															82													</td>
<td class='3D"value' data-value='3D"82"' hh-salaries-sorted="">
															82													</td>
<td class='3D"value' data-value='3D"82"' hh-salaries-sorted="">
															82													</td>
<td class='3D"value' data-value='3D"82"' hh-salaries-sorted="">
															82													</td>
<td class='3D"value' data-value='3D"82"' hh-salaries-sorted="">
															82													</td>
<td class='3D"value' data-value='3D"81"' hh-salaries-sorted="">
															81													</td>
<td class='3D"value' data-value='3D"81"' hh-salaries-sorted="">
															81													</td>
<td class='3D"value' data-value='3D"81"' hh-salaries-sorted="">
															81													</td>
<td class='3D"value' data-value='3D"81"' hh-salaries-sorted="">
															81													</td>
<td class='3D"value' data-value='3D"81"' hh-salaries-sorted="">
															81													</td>
<td class='3D"value' data-value='3D"81"' hh-salaries-sorted="">
															81													</td>
<td class='3D"value' data-value='3D"81"' hh-salaries-sorted="">
															81													</td>
<td class='3D"value' data-value='3D"81"' hh-salaries-sorted="">
															81													</td>
<td class='3D"value' data-value='3D"81"' hh-salaries-sorted="">
															81													</td>
<td class='3D"value' data-value='3D"81"' hh-salaries-sorted="">
															81													</td>
<td class='3D"value' data-value='3D"81"' hh-salaries-sorted="">
															81													</td>
<td class='3D"value' data-value='3D"80"' hh-salaries-sorted="">
															80													</td>
<td class='3D"value' data-value='3D"80"' hh-salaries-sorted="">
															80													</td>
<td class='3D"value' data-value='3D"80"' hh-salaries-sorted="">
															80													</td>
<td class='3D"value' data-value='3D"80"' hh-salaries-sorted="">
															80													</td>
<td class='3D"value' data-value='3D"80"' hh-salaries-sorted="">
															80													</td>
<td class='3D"value' data-value='3D"80"' hh-salaries-sorted="">
															80													</td>
<td class='3D"value' data-value='3D"80"' hh-salaries-sorted="">
															80													</td>
<td class='3D"value' data-value='3D"80"' hh-salaries-sorted="">
															80													</td>
<td class='3D"value' data-value='3D"80"' hh-salaries-sorted="">
															80													</td>
<td class='3D"value' data-value='3D"80"' hh-salaries-sorted="">
															80													</td>
<td class='3D"value' data-value='3D"80"' hh-salaries-sorted="">
															80													</td>
<td class='3D"value' data-value='3D"80"' hh-salaries-sorted="">
															80													</td>
<td class='3D"value' data-value='3D"80"' hh-salaries-sorted="">
															80													</td>
<td class='3D"value' data-value='3D"80"' hh-salaries-sorted="">
															80													</td>
<td class='3D"value' data-value='3D"79"' hh-salaries-sorted="">
															79													</td>
<td class='3D"value' data-value='3D"79"' hh-salaries-sorted="">
															79													</td>
<td class='3D"value' data-value='3D"79"' hh-salaries-sorted="">
															79													</td>
<td class='3D"value' data-value='3D"79"' hh-salaries-sorted="">
															79													</td>
<td class='3D"value' data-value='3D"79"' hh-salaries-sorted="">
															79													</td>
<td class='3D"value' data-value='3D"79"' hh-salaries-sorted="">
															79													</td>
<td class='3D"value' data-value='3D"79"' hh-salaries-sorted="">
															79													</td>
<td class='3D"value' data-value='3D"79"' hh-salaries-sorted="">
															79													</td>
<td class='3D"value' data-value='3D"79"' hh-salaries-sorted="">
															79													</td>
<td class='3D"value' data-value='3D"79"' hh-salaries-sorted="">
															79													</td>
<td class='3D"value' data-value='3D"79"' hh-salaries-sorted="">
															79													</td>
<td class='3D"value' data-value='3D"79"' hh-salaries-sorted="">
															79													</td>
<td class='3D"value' data-value='3D"79"' hh-salaries-sorted="">
															79													</td>
<td class='3D"value' data-value='3D"79"' hh-salaries-sorted="">
															79													</td>
<td class='3D"value' data-value='3D"79"' hh-salaries-sorted="">
															79													</td>
<td class='3D"value' data-value='3D"79"' hh-salaries-sorted="">
															79													</td>
<td class='3D"value' data-value='3D"79"' hh-salaries-sorted="">
															79													</td>
<td class='3D"value' data-value='3D"79"' hh-salaries-sorted="">
															79													</td>
<td class='3D"value' data-value='3D"79"' hh-salaries-sorted="">
															79													</td>
<td class='3D"value' data-value='3D"79"' hh-salaries-sorted="">
															79													</td>
<td class='3D"value' data-value='3D"79"' hh-salaries-sorted="">
															79													</td>
<td class='3D"value' data-value='3D"79"' hh-salaries-sorted="">
															79													</td>
<td class='3D"value' data-value='3D"78"' hh-salaries-sorted="">
															78													</td>
<td class='3D"value' data-value='3D"78"' hh-salaries-sorted="">
															78													</td>
<td class='3D"value' data-value='3D"78"' hh-salaries-sorted="">
															78													</td>
<td class='3D"value' data-value='3D"78"' hh-salaries-sorted="">
															78													</td>
<td class='3D"value' data-value='3D"78"' hh-salaries-sorted="">
															78													</td>
<td class='3D"value' data-value='3D"78"' hh-salaries-sorted="">
															78													</td>
<td class='3D"value' data-value='3D"78"' hh-salaries-sorted="">
															78													</td>
<td class='3D"value' data-value='3D"78"' hh-salaries-sorted="">
															78													</td>
<td class='3D"value' data-value='3D"78"' hh-salaries-sorted="">
															78													</td>
<td class='3D"value' data-value='3D"78"' hh-salaries-sorted="">
															78													</td>
<td class='3D"value' data-value='3D"78"' hh-salaries-sorted="">
															78													</td>
<td class='3D"value' data-value='3D"78"' hh-salaries-sorted="">
															78													</td>
<td class='3D"value' data-value='3D"78"' hh-salaries-sorted="">
															78													</td>
<td class='3D"value' data-value='3D"78"' hh-salaries-sorted="">
															78													</td>
<td class='3D"value' data-value='3D"78"' hh-salaries-sorted="">
															78													</td>
<td class='3D"value' data-value='3D"78"' hh-salaries-sorted="">
															78													</td>
<td class='3D"value' data-value='3D"78"' hh-salaries-sorted="">
															78													</td>
<td class='3D"value' data-value='3D"78"' hh-salaries-sorted="">
															78													</td>
<td class='3D"value' data-value='3D"78"' hh-salaries-sorted="">
															78													</td>
<td class='3D"value' data-value='3D"78"' hh-salaries-sorted="">
															78													</td>
<td class='3D"value' data-value='3D"78"' hh-salaries-sorted="">
															78													</td>
<td class='3D"value' data-value='3D"78"' hh-salaries-sorted="">
															78													</td>
<td class='3D"value' data-value='3D"78"' hh-salaries-sorted="">
															78													</td>
<td class='3D"value' data-value='3D"78"' hh-salaries-sorted="">
															78													</td>
<td class='3D"value' data-value='3D"77"' hh-salaries-sorted="">
															77													</td>
<td class='3D"value' data-value='3D"77"' hh-salaries-sorted="">
															77													</td>
<td class='3D"value' data-value='3D"77"' hh-salaries-sorted="">
															77													</td>
<td class='3D"value' data-value='3D"77"' hh-salaries-sorted="">
															77													</td>
<td class='3D"value' data-value='3D"77"' hh-salaries-sorted="">
															77													</td>
<td class='3D"value' data-value='3D"77"' hh-salaries-sorted="">
															77													</td>
<td class='3D"value' data-value='3D"77"' hh-salaries-sorted="">
															77													</td>
<td class='3D"value' data-value='3D"77"' hh-salaries-sorted="">
															77													</td>
<td class='3D"value' data-value='3D"77"' hh-salaries-sorted="">
															77													</td>
<td class='3D"value' data-value='3D"77"' hh-salaries-sorted="">
															77													</td>
<td class='3D"value' data-value='3D"77"' hh-salaries-sorted="">
															77													</td>
<td class='3D"value' data-value='3D"77"' hh-salaries-sorted="">
															77													</td>
<td class='3D"value' data-value='3D"77"' hh-salaries-sorted="">
															77													</td>
<td class='3D"value' data-value='3D"77"' hh-salaries-sorted="">
															77													</td>
<td class='3D"value' data-value='3D"77"' hh-salaries-sorted="">
															77													</td>
<td class='3D"value' data-value='3D"77"' hh-salaries-sorted="">
															77													</td>
<td class='3D"value' data-value='3D"77"' hh-salaries-sorted="">
															77													</td>
<td class='3D"value' data-value='3D"77"' hh-salaries-sorted="">
															77													</td>
<td class='3D"value' data-value='3D"77"' hh-salaries-sorted="">
															77													</td>
<td class='3D"value' data-value='3D"77"' hh-salaries-sorted="">
															77													</td>
<td class='3D"value' data-value='3D"77"' hh-salaries-sorted="">
															77													</td>
<td class='3D"value' data-value='3D"77"' hh-salaries-sorted="">
															77													</td>
<td class='3D"value' data-value='3D"77"' hh-salaries-sorted="">
															77													</td>
<td class='3D"value' data-value='3D"77"' hh-salaries-sorted="">
															77													</td>
<td class='3D"value' data-value='3D"77"' hh-salaries-sorted="">
															77													</td>
<td class='3D"value' data-value='3D"77"' hh-salaries-sorted="">
															77													</td>
<td class='3D"value' data-value='3D"77"' hh-salaries-sorted="">
															77													</td>
<td class='3D"value' data-value='3D"77"' hh-salaries-sorted="">
															77													</td>
<td class='3D"value' data-value='3D"77"' hh-salaries-sorted="">
															77													</td>
<td class='3D"value' data-value='3D"77"' hh-salaries-sorted="">
															77													</td>
<td class='3D"value' data-value='3D"77"' hh-salaries-sorted="">
															77													</td>
<td class='3D"value' data-value='3D"77"' hh-salaries-sorted="">
															77													</td>
<td class='3D"value' data-value='3D"77"' hh-salaries-sorted="">
															77													</td>
<td class='3D"value' data-value='3D"77"' hh-salaries-sorted="">
															77													</td>
<td class='3D"value' data-value='3D"76"' hh-salaries-sorted="">
															76													</td>
<td class='3D"value' data-value='3D"76"' hh-salaries-sorted="">
															76													</td>
<td class='3D"value' data-value='3D"76"' hh-salaries-sorted="">
															76													</td>
<td class='3D"value' data-value='3D"76"' hh-salaries-sorted="">
															76													</td>
<td class='3D"value' data-value='3D"76"' hh-salaries-sorted="">
															76													</td>
<td class='3D"value' data-value='3D"76"' hh-salaries-sorted="">
															76													</td>
<td class='3D"value' data-value='3D"76"' hh-salaries-sorted="">
															76													</td>
<td class='3D"value' data-value='3D"76"' hh-salaries-sorted="">
															76													</td>
<td class='3D"value' data-value='3D"76"' hh-salaries-sorted="">
															76													</td>
<td class='3D"value' data-value='3D"76"' hh-salaries-sorted="">
															76													</td>
<td class='3D"value' data-value='3D"76"' hh-salaries-sorted="">
															76													</td>
<td class='3D"value' data-value='3D"76"' hh-salaries-sorted="">
															76													</td>
<td class='3D"value' data-value='3D"76"' hh-salaries-sorted="">
															76													</td>
<td class='3D"value' data-value='3D"76"' hh-salaries-sorted="">
															76													</td>
<td class='3D"value' data-value='3D"76"' hh-salaries-sorted="">
															76													</td>
<td class='3D"value' data-value='3D"76"' hh-salaries-sorted="">
															76													</td>
<td class='3D"value' data-value='3D"76"' hh-salaries-sorted="">
															76													</td>
<td class='3D"value' data-value='3D"76"' hh-salaries-sorted="">
															76													</td>
<td class='3D"value' data-value='3D"76"' hh-salaries-sorted="">
															76													</td>
<td class='3D"value' data-value='3D"76"' hh-salaries-sorted="">
															76													</td>
<td class='3D"value' data-value='3D"76"' hh-salaries-sorted="">
															76													</td>
<td class='3D"value' data-value='3D"76"' hh-salaries-sorted="">
															76													</td>
<td class='3D"value' data-value='3D"76"' hh-salaries-sorted="">
															76													</td>

In [23]:
# Write a regex to get rid of leading and trailing stuff around the two digits that make up the OVR score.
for ovr in overallrows:
    ovr=str(ovr)
    regex=r"[0-9]*[0-9]"
    ovr=re.search(regex,ovr).group(0)
    print(ovr)
# It worked, but the top number is 2020, which will need to be cleaned

2020
97
97
96
96
95
95
95
94
94
91
90
90
90
90
89
89
88
88
88
88
88
88
87
87
87
87
87
87
86
86
86
86
86
86
86
85
85
85
85
85
85
85
85
85
84
84
84
84
84
84
84
84
83
83
83
83
83
83
83
83
83
83
83
82
82
82
82
82
82
82
82
81
81
81
81
81
81
81
81
81
81
81
80
80
80
80
80
80
80
80
80
80
80
80
80
80
79
79
79
79
79
79
79
79
79
79
79
79
79
79
79
79
79
79
79
79
79
79
78
78
78
78
78
78
78
78
78
78
78
78
78
78
78
78
78
78
78
78
78
78
78
78
77
77
77
77
77
77
77
77
77
77
77
77
77
77
77
77
77
77
77
77
77
77
77
77
77
77
77
77
77
77
77
77
77
77
76
76
76
76
76
76
76
76
76
76
76
76
76
76
76
76
76
76
76
76
76
76
76
76
76
76
76
76
76
76
76
76
76
76
76
76
76
76
76
76
76
76
76
76
76
76
76
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
75
74
74
74
74
74
74
74
74
74
74
74
74
74
74
74
74
74
74
74
74
74
74
74
74
74
74
74
74
74
74
74
74
74
74
74
74
74
74
74
74
74
74
73
73
73
73
73
73
73
73
73
73
73
73
73
73
73
73
73
73
73
73
73
73
73
73
73
73
73
73
73
73
73
73
73
73
73
73
73
73
73
73
73
73
73
73
73
73
73
73
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
71
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
70
69
69
69
69
69
69
69
69
69
69
69
69
69
69
69
69
69
69
69
69
69
69
69
69
69
69
68
68
68
68
68
68
68
68
68
68
68
68
68
68
68
68
68
68
68
68
68
68
68
68
68
68
68
68
68
68
68
68
68
68
68
68
68
67
67
67
67
67
67
67
67
67
67
67
67
67
67
67
67
67
67
66

In [24]:
# Now work on getting the player name
namerows = soup.find_all(lambda tag: tag.name == 'td' and tag.get('class') == ['3D"name"'])
# Need to find a way to get the 'a' tag from the td.
for name in namerows:
    for a in name.find_all('a', href=True):
        try:
            a=str(a)
            regex=r"[a-z]+-[a-z]+"
            regexName = re.search(regex, a).group(0)
            regexName = str(regexName)
            regexName = regexName.replace("-", " ")
            print(regexName)
        except AttributeError:
            a=str(a)
            regex= r"[a-z]+-[a-z]+"
            regexName = re.search(regex, a)
            regexName = str(regexName)
            regexName = regexName.replace("-", " ")
            print(regexName)

lebron james
giannis antetokounmp
kawhi leonard
james harden
stephen curry
kevin durant
anthony davis
luka doncic
damian lillard
joel embiid
paul george
nikola jokic
kyrie irving
karl anthony
klay thompson
jimmy butler
trae young
russell westbrook
pascal siakam
donovan mitchell
chris paul
bradley beal
rudy gobert
kyle lowry
kristaps porzingis
jayson tatum
devin booker
ben simmons
zion williamson
nikola vucevic
khris middleton
kemba walker
demar derozan
brandon ingram
bam adebayo
fred vanvleet
zach lavine
tj warren
john collins
jamal murray
ja morant
domantas sabonis
deaaron fox
andre drummond
tobias harris
shai gilgeous
lamarcus aldridge
jusuf nurkic
jaylen brown
deandre ayton
dangelo russell
cj mccollum
hassan whiteside
danilo gallinari
spencer dinwiddie
malcolm brogdon
jrue holiday
john wall
jaren jackson
gordon hayward
eric bledsoe
caris levert
blake griffin
montrezl harrell
victor oladipo
steven adams
kevin love
jonathan isaac
clint capela
brook lopez
andrew wiggins
demarcus cousins
mitchell robinson
michael porter
marvin bagley
louis williams
kelly oubre
jonas valanciunas
jarrett allen
derrick rose
buddy hield
bojan bogdanovic
serge ibaka
christian wood
marcus smart
lauri markkanen
julius randle
josh richardson
evan fournier
dennis schroeder
dejounte murray
deandre jordan
collin sexton
brandon clarke
al horford
aaron gordon
will barton
tristan thompson
paul millsap
goran dragic
davis bertans
bogdan bogdanovic
wendell carter
thomas bryant
terry rozier
rui hachimura
rudy gay
robert covington
ricky rubio
og anunoby
myles turner
mike conley
larry nance
eric paschall
draymond green
devonte graham
derrick white
daniel theis
marcus morris
jordan clarkson
jeff teague
dwight howard
carmelo anthony
aron baynes
tyler herro
troy brown
tim hardaway
terrence ross
seth curry
richaun holmes
patrick beverley
otto porter
nemanja bjelica
luke kennard
joe ingles
jj redick
javale mcgee
ivica zubac
harrison barnes
eric gordon
duncan robinson
cody zeller
james wiseman
anthony edwards
lamelo ball
mason plumlee
marc gasol
joe harris
jae crowder
isaiah thomas
derrick favors
chris boucher
alec burks
willie cauley
taj gibson
pj washington
patrick mills
norman powell
monte morris
miles bridges
mikal bridges
markelle fultz
malik beasley
lonzo ball
justise winslow
jeremy lamb
jerami grant
jalen brunson
jabari parker
george hill
gary trent
elfrid payton
donte divincenzo
dillon brooks
coby white
bobby portis
obi toppin
onyeka okongwu
danny green
trey burke
shabazz napier
rondae hollis
reggie jackson
nerlens noel
michael carter
jeff green
jahlil okafor
gerald green
dj augustin
bismack biyombo
alex len
terence davis
kendrick nunn
tyus jones
tomas satoransky
thaddeus young
rodney hood
rajon rondo
pj tucker
moritz wagner
mo bamba
maxi kleber
marquese chriss
kyle kuzma
kris dunn
kelly olynyk
keldon johnson
jaxson hayes
james johnson
jakob poeltl
ishmael smith
gary harris
ersan ilyasova
enes kanter
dwight powell
doug mcdermott
dorian finney
denzel valentine
dario saric
danuel house
cameron johnson
andre iguodala
aaron holiday
jaesean tate
deni avdija
isaac okoro
patrick williams
willy hernangomez
pau gasol
meyers leonard
markieff morris
langston galloway
justin holiday
jose juan
john henson
jamal crawford
harry giles
glenn robinson
derrick jones
allonzo trier
zach collins
wesley matthews
trey lyles
tony bradley
tj mcconnell
shake milton
rj barrett
nicolo melli
matisse thybulle
malik monk
kyle anderson
kevin porter
kevin huerter
kentavious caldwell
josh hart
james ennis
furkan korkmaz
frank kaminsky
delon wright
deanthony melton
deandre hunter
daniel gafford
chandler hutchison
cedi osman
boban marjanovic
austin rivers
al farouq
precious achiuwa
devin vassell
tyrese haliburton
killian hayes
jordan mclaughlin
torrey craig
noah vonleh
marvin williams
kyle oquinn
kent bazemore
jordan mcrae
ivan rabb
ian mahinmi
emmanuel mudiay
chandler parsons
bryn forbes
luguentz dort
trevor ariza
timothe luwawu
skal labissiere
royce oneale
robert williams
patrick patterson
omari spellman
matt thomas
landry shamet
kevon looney
juan hernangomez
jr smith
josh okogie
jordan bell
jarrett culver
gorgui dieng
garrett temple
darius garland
damion lee
damian jones
cameron payne
bruce brown
ben mclemore
avery bradley
alex caruso
facundo campazzo
kira lewis
jalen smith
cheick diallo
shaquille harrison
raul neto
pat connaughton
kyle korver
josh jackson
jonah bolden
jevon carter
jakarr sampson
isaiah hartenstein
evan turner
etwaun moore
corey brewer
cj miles
brad wanamaker
ante zizic
chris clemons
vincent poirier
thon maker
taurean prince
sviatoslav mykhailiu
robin lopez
quinn cook
patrick mccaw
nicolas claxton
nicolas batum
mike muscala
mario hezonja
luke kornet
lonnie walker
jerome robinson
jake layman
goga bitadze
georges niang
frank ntilikina
dion waiters
demarre carroll
deandre bembry
david nwaba
darius bazley
dante exum
cory joseph
chimezie metu
cam reddish
bruno fernando
gabriel deck
jaden mcdaniels
rj hampton
aleksej pokusevski
cole anthony
saddiq bey
isaiah stewart
aaron nesmith
tyrese maxey
josh green
chuma okeke
jonathon simmons
antonio blakeney
john konchar
wesley iwundu
tyson chandler
tyler johnson
tim frazier
thabo sefolosha
ryan broekhoff
None
moe harkless
michael kidd
luc richard
kadeem allen
jerian grant
jared dudley
iman shumpert
gary payton
gary clark
damyean dotson
chris chiozza
bruno caboclo
andre roberson
allen crabbe
anzejs pasecniks
cody martin
javonte green
pj dozier
wayne ellington
tyler zeller
tony snell
talen horton
sekou doumbouya
reggie bullock
naz reid
nassir little
mike scott
mfiondu kabengele
luka samanic
khem birch
kevin knox
justin jackson
jordan poole
joakim noah
jamychal green
isaac bonga
grayson allen
ed davis
dewayne dedmon
dennis smith
darius miller
cristiano felicio
anfernee simons
malachi flynn
immanuel quickley
zeke nnaji
udoka azubuike
deyonta davis
garrison mathews
bol bol
yogi ferrell
troy daniels
treveon graham
sterling brown
solomon hill
sindarius thornwell
marco belinelli
kenrich williams
justin anderson
johnathan motley
frank jackson
courtney lee
chasson randle
anthony tolliver
ky bowman
jaylen nowell
jontay porter
norvel pelle
ty jerome
tj leaf
terrance ferguson
terance mann
stanley johnson
semi ojeleye
rodney mcgruder
rodions kurucs
nickeil alexander
kz okpala
keita bates
justin james
jacob evans
grant williams
elie okobo
edmond sumner
dzanan musa
dylan windler
brandon goodwin
alen smailagic
admiral schofield
abdel nader
charlie brown
desmond bane
payton pritchard
theo maledon
miles plumlee
jemerrio jones
johnathan williams
donta hall
daquan jeffries
tacko fall
wilson chandler
wenyen gabriel
udonis haslem
matthew dellavedova
brandon knight
alize johnson
isaiah roby
vlatko cancar
juwan morgan
jalen mcdaniels
dean wade
zhaire smith
thanasis antetokounm
ryan arcidiacono
ryan anderson
romeo langford
melvin frazier
jarred vanderbilt
ignas brazdeikis
hamidou diallo
dwayne bacon
dj wilson
deonte burton
carsen edwards
alfonzo mckinnie
juan toscano
jaylen adams
jaylen hoard
kelan martin
vic law
devontae cacok
kenny wooten
kyle guy
tremont waters
derrick walton
sirdominic pointer
raymond spalding
malcolm miller
kostas antetokounmpo
jeremy pargo
henry ellenson
frank mason
dragan bender
cam reynolds
caleb swanigan
amile jefferson
rayjon tucker
caleb martin
marko guduric
theo pinson
justin patton
skylar mays
kevin hervey
tariq owens
quinndary weatherspo
william howard
louis king
jordan bone
brian bowen
tyler cook
bj johnson
kyle alexander
amir coffey
matt mooney
adam mokoka
max strus
stanton kidd
daryl macon
levi randolph
shamorie ponds
josh magette
eric mika
marques bolden
zach norvell
jp macura
malik newman
dusty hannahs
joe chealey
yuta watanabe
tyrone wallace
naz long
michael frazier
drew eubanks
mychal mulder
dewan hernandez
miye oni
khyri thomas
jalen lecque
kj martin
jarrod uthoff
moses brown
devon hall
paul watson
oshae brissett
zylan cheatham
josh gray
jeremiah martin
josh reaves
jared harper
jarrell brantley
justin wright
gabe vincent
marial shayok
justin robinson
robert franks
antonius cleveland
kobi simmons

In [25]:
list_names = []
list_ovr = []

for name in namerows:
    for a in name.find_all('a', href=True):
        try:
            a=str(a)
            regex= r"[a-z]+-[a-z]+"
            urlname = re.search(regex, a).group(0)
            urlname = str(urlname)
            urlname = urlname.replace("-", " ")
            #Add it to the dataframe
            list_names.append({'Name': urlname})

        except AttributeError:
            a=str(a)
            regex= r"[a-z]+-[a-z]+"
            urlname = re.search(regex, a)
            urlname = str(urlname)
            urlname = urlname.replace("-", " ")
            #Add it to the dataframe
            list_names.append({'Name': urlname})
for ovr in overallrows:
    ovr=str(ovr)
    #now need to write a regex to get rid of leading and trailing stuff around the two #'s
    regex=r"[0-9]*[0-9]"
    ovr=re.search(regex,ovr).group(0)
    list_ovr.append(ovr)
    
#Drop the first row of OVRs
list_ovr.pop(0)
      
# Make the names list a data frame
df_BOTH = pd.DataFrame(list_names)

# Add the ovr list to the dataframe as a column
df_BOTH['OVR'] = list_ovr

# Fix Giannis' name (it was shortened somehow in the html)
df_BOTH.iloc[1, 0] = "giannis antetokounmpo"


print(len(list_names))
print(len(list_ovr))
df_BOTH

585
585

                      Name OVR
0             lebron james  97
1    giannis antetokounmpo  97
2            kawhi leonard  96
3             james harden  96
4            stephen curry  95
..                     ...  ..
580          marial shayok  67
581        justin robinson  67
582          robert franks  67
583     antonius cleveland  67
584           kobi simmons  66

[585 rows x 2 columns]

In [27]:
# Now we want to merge our two dataframes by name, so we can add the OVR column and only include the players in both

# Rename them to keep track of them
df1 = dfReordered # 704 rows x 33 columns
df_NAMEandOVR = df_BOTH # 585 rows x 2 columns

# Merge the two with an inner join by Name, preserving the order of the left keys
dfMerged = df_NAMEandOVR.merge(df1, how='inner', on='Name')

dfMerged # 456 rows Ã— 34 columns

# We lost about 130 players when we merged the dataframes, likely due to spelling differences in the names

cols2 = list(dfMerged.columns.values)

In [35]:
dfMerged['OVR']=pd.to_numeric(dfMerged['OVR'])

,Name,OVR,Pos,Tm,Age,G,GS,MP,FG,FGA,...,AST,STL,BLK,STL%,BLK%,DWS,DBPM,TOV,PF,PTS
0,lebron james,97,PG,LAL,36.0,45.0,45.0,33.4,9.4,18.3,...,7.8,1.1,0.6,1.6,1.5,2.6,2.3,3.7,1.6,25.0
1,giannis antetokounmpo,97,PF,MIL,26.0,61.0,61.0,33.0,10.3,18.0,...,5.9,1.2,1.2,1.7,3.2,3.3,2.8,3.4,2.8,28.1
2,kawhi leonard,96,SF,LAC,29.0,52.0,52.0,34.1,8.9,17.5,...,5.2,1.6,0.4,2.3,1.1,2.4,1.3,2.0,1.6,24.8
3,james harden,96,PG-SG,TOT,31.0,44.0,43.0,36.6,7.8,16.7,...,10.8,1.2,0.8,1.6,1.8,1.7,1.0,4.0,2.3,24.6
4,james harden,96,SG,HOU,31.0,8.0,8.0,36.3,7.5,16.9,...,10.4,0.9,0.8,1.1,1.8,0.2,-0.5,4.3,1.8,24.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
451,jared harper,67,PG,NYK,23.0,8.0,0.0,2.0,0.0,0.5,...,0.1,0.0,0.0,0.0,0.0,0.0,-5.5,0.4,0.1,0.4
452,jarrell brantley,67,PF,UTA,24.0,28.0,0.0,4.9,0.9,1.9,...,0.5,0.3,0.1,2.5,1.2,0.2,1.6,0.3,0.6,2.3
453,gabe vincent,67,PG,MIA,24.0,50.0,7.0,13.1,1.8,4.7,...,1.3,0.4,0.0,1.6,0.3,0.5,-0.9,0.7,1.6,4.8
454,justin robinson,67,PG,OKC,23.0,9.0,0.0,9.8,0.8,2.3,...,1.0,0.3,0.0,1.6,0.0,0.0,-1.0,0.2,1.1,2.3
455,robert franks,67,PF,ORL,24.0,7.0,0.0,14.4,1.9,4.0,...,0.7,0.4,0.4,1.4,2.7,0.1,-0.8,0.3,1.1,6.1

In [28]:
#ELI YOU CAN ADD ALL YOUR DATA VIZ STUFF HERE

In [36]:
#We then tried to fit a linear model on our data and realized that a small number of the rows (only 25 out of 450)
#contained missing values. We elected to drop these rows as it didn't seem like it would significantly impact our regression
#model going forward.

# Create a copy of the full data frame to begin training and testing
dfCopy = dfMerged
dfCopy # 456 rows Ã— 34 columns

numericColumns = dfCopy.select_dtypes(include=np.number).columns.tolist()

# Make a new dataframe that is only the numeric columns for linear modeling
dfNumeric = dfCopy[numericColumns]
dfNumeric

def clean_dataset(df):
    assert isinstance(df, pd.DataFrame)
    df.dropna(inplace=True)
    indices_to_keep = ~df.isin([np.nan, np.inf, -np.inf]).any(1)
    return df[indices_to_keep].astype(np.float64)

# Drop the columns with missing and infinite values
dfCleaned = clean_dataset(dfNumeric)
dfCleaned # 421 rows Ã— 31 columns

C:\Users\husto\anaconda3\lib\site-packages\pandas\util\_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

,OVR,Age,G,GS,MP,FG,FGA,FG%,3P,3PA,...,AST,STL,BLK,STL%,BLK%,DWS,DBPM,TOV,PF,PTS
0,97.0,36.0,45.0,45.0,33.4,9.4,18.3,0.513,2.3,6.3,...,7.8,1.1,0.6,1.6,1.5,2.6,2.3,3.7,1.6,25.0
1,97.0,26.0,61.0,61.0,33.0,10.3,18.0,0.569,1.1,3.6,...,5.9,1.2,1.2,1.7,3.2,3.3,2.8,3.4,2.8,28.1
2,96.0,29.0,52.0,52.0,34.1,8.9,17.5,0.512,1.9,4.9,...,5.2,1.6,0.4,2.3,1.1,2.4,1.3,2.0,1.6,24.8
3,96.0,31.0,44.0,43.0,36.6,7.8,16.7,0.466,2.8,7.6,...,10.8,1.2,0.8,1.6,1.8,1.7,1.0,4.0,2.3,24.6
4,96.0,31.0,8.0,8.0,36.3,7.5,16.9,0.444,3.1,9.0,...,10.4,0.9,0.8,1.1,1.8,0.2,-0.5,4.3,1.8,24.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
451,67.0,23.0,8.0,0.0,2.0,0.0,0.5,0.000,0.0,0.1,...,0.1,0.0,0.0,0.0,0.0,0.0,-5.5,0.4,0.1,0.4
452,67.0,24.0,28.0,0.0,4.9,0.9,1.9,0.481,0.4,1.0,...,0.5,0.3,0.1,2.5,1.2,0.2,1.6,0.3,0.6,2.3
453,67.0,24.0,50.0,7.0,13.1,1.8,4.7,0.378,0.9,3.0,...,1.3,0.4,0.0,1.6,0.3,0.5,-0.9,0.7,1.6,4.8
454,67.0,23.0,9.0,0.0,9.8,0.8,2.3,0.333,0.4,1.6,...,1.0,0.3,0.0,1.6,0.0,0.0,-1.0,0.2,1.1,2.3
455,67.0,24.0,7.0,0.0,14.4,1.9,4.0,0.464,0.7,2.1,...,0.7,0.4,0.4,1.4,2.7,0.1,-0.8,0.3,1.1,6.1

In [37]:
#Now that our data was fully cleaned, we began the process of fitting a linear model. 
from sklearn.model_selection import train_test_split
train, val = train_test_split(dfCleaned, train_size=0.8, random_state=42)

In [39]:
train # 336 rows Ã— 31 columns
val # 85 rows Ã— 31 columns

,OVR,Age,G,GS,MP,FG,FGA,FG%,3P,3PA,...,AST,STL,BLK,STL%,BLK%,DWS,DBPM,TOV,PF,PTS
149,77.0,24.0,72.0,72.0,32.6,5.0,9.3,0.543,1.9,4.4,...,2.1,1.1,0.9,1.6,2.4,2.6,0.9,0.8,1.6,13.5
353,72.0,28.0,19.0,17.0,30.4,5.0,9.0,0.556,0.5,1.6,...,1.9,0.8,1.2,1.3,3.8,0.6,0.0,1.1,2.4,11.9
180,76.0,23.0,25.0,13.0,15.0,2.5,4.9,0.508,0.5,1.7,...,1.3,0.9,0.3,2.7,1.8,0.5,1.3,0.8,2.5,7.1
396,71.0,21.0,37.0,9.0,12.1,1.0,2.6,0.375,0.3,1.4,...,0.5,0.3,0.3,1.1,2.6,0.4,-0.6,0.4,1.6,2.5
452,67.0,24.0,28.0,0.0,4.9,0.9,1.9,0.481,0.4,1.0,...,0.5,0.3,0.1,2.5,1.2,0.2,1.6,0.3,0.6,2.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,82.0,27.0,69.0,1.0,22.9,5.4,8.7,0.622,0.0,0.1,...,1.1,0.7,0.7,1.4,2.8,2.7,0.7,1.1,1.9,13.5
446,68.0,20.0,4.0,0.0,3.0,0.3,2.3,0.111,0.0,0.3,...,0.5,0.0,0.0,0.0,0.0,0.0,-6.3,0.0,0.0,1.3
24,86.0,29.0,68.0,68.0,33.4,7.5,15.8,0.476,2.2,5.4,...,5.4,1.1,0.1,1.5,0.4,2.2,-0.3,2.6,2.4,20.4
17,88.0,24.0,53.0,53.0,33.4,9.0,20.6,0.438,3.4,8.7,...,5.2,1.0,0.3,1.4,0.7,2.2,-0.2,2.8,2.2,26.4
68,81.0,30.0,25.0,11.0,20.2,3.2,8.4,0.376,1.6,4.6,...,2.4,0.8,0.7,2.0,3.2,0.8,1.5,1.6,3.0,9.6

In [40]:
# Split the data into dataframes of predicting variables and the OVR that we will attempt to predict.
def select_columns(data, *columns):
    return data.loc[:, columns]

X_train = select_columns(train, 
                        'STL%',
                        'BLK%',
                        'DWS',
                        'DBPM',
                        'STL',
                        'BLK')
Y_train = train.loc[:,'OVR']

X_val = select_columns(val, 
                        'STL%',
                        'BLK%',
                        'DWS',
                        'DBPM',
                        'STL',
                        'BLK')
y_val = val.loc[:,'OVR']